version: '3'

services:
  client:
    build: sysmon
    image: sysmon-client
    container_name: sysmon-client
    restart: always
    network_mode: host  # Used to send data to localhost. Can be deleted if server is reachable with a web address
    runtime: nvidia  # if you don't have a nvidia gpu, comment out this
    deploy:          # and the whole deploy block
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      HOSTNAME: asraphael  # The name of the host system
      JSON_ENDPOINT: http://141.26.66.69:5000/post  # Address of sysmon-server

  # If you use only the client, you can comment out all of the server
#  server:
#    build: sysmon-server
#    image: sysmon-server
#    container_name: sysmon-server
#    restart: always
#    ports:
#    - "5000:5000"