version: '3'

services:
  client:
    build: Dockerfile
    image: sysmon-client
    container_name: sysmon-client
    restart: always
    network_mode: host  # Used to send data to localhost. Can be deleted if server is reachable with a web address
    runtime: nvidia  # if you don't have a nvidia gpu, comment out this
    deploy:          # and the whole deploy block
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]