[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.interrogate]
fail-under = 95
ignore-init-method = true
ignore-init-module = true
ignore-property-decorators = true
exclude = ["docs", "build", "dist", ".tox"]
verbose = 1